Hostboot Building Patches for eBMC in Standalone
Changes the setup-standalone-repo script to be more flexible to changes
introduced in 1060 while remaining backward compatible by doing the
following:

Copy OP-BUILD PNOR XML from the proper backing build
to allow the PNOR to be built in standalone.

Export BMC_STANDALONE_PATCHING=1 to indicate to
assemble.standalone.mk to model the PNOR appropriately.

Change the commit that was cherry-picked to a new one which modifies
assemble.standalone.mk to generate the PNOR properly based on the new
environment variable

Change-Id: Ic565d09626304a8159933feb1f4f0784deadbbe3
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/151611
Reviewed-by: Zachary Clark <zach@ibm.com>
Tested-by: Jenkins OP Build CI <op-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins Combined Simics CI <combined-simics-ci+hostboot@us.ibm.com>
Reviewed-by: MIKE VAGELINE <mpvageli@us.ibm.com>
Tested-by: Jenkins OP HW <op-hw-jenkins+hostboot@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Tested-by: Hostboot CI <hostboot-ci+hostboot@us.ibm.com>
Reviewed-by: Daniel M Crowell <dcrowell@us.ibm.com>

diff --git a/src/build/tools/ebmc/setup-standalone-repo b/src/build/tools/ebmc/setup-standalone-repo
--- a/src/build/tools/ebmc/setup-standalone-repo
+++ b/src/build/tools/ebmc/setup-standalone-repo
@@ -24,6 +24,9 @@
 #
 # IBM_PROLOG_END_TAG
 
+
+# NOTE: Since this script is executed in the current shell, this script should never use 'exit'. Instead, 'return' is
+#       used because 'exit' will cause the current shell to exit which would kick the user out of their workon.
 function usage ()
 {
     echo "Usage: source ${BASH_SOURCE[0]} PACKAGE_NAME [-h|--help] [-x|--xml-only OR -n|--no-xml] [-s|--system-type e|2u|4u] [-b|--branch-name]"
@@ -62,8 +65,9 @@ function copy_targeting_xml ()
     if [ -z "${sys_type}" ]; then
         echo "Copying system MRWs into $PROJECT_ROOT/src/usr/targeting/common/xmltohb/ ..."
         cp -v /afs/rchland/projects/esw/$pnor_release/Builds/$pnor_build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_mrw_scratch/*_hb.mrw.xml $PROJECT_ROOT/src/usr/targeting/common/xmltohb/
-        if [ $? -ne 0 ]; then
-            return $?
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
+            return ${rc}
         fi
         echo ""
         echo "Done."
@@ -71,14 +75,16 @@ function copy_targeting_xml ()
     else
         echo "Copying $sys_type MRW into $PROJECT_ROOT/src/usr/targeting/common/xmltohb/ ..."
         cp -v /afs/rchland/projects/esw/$pnor_release/Builds/$pnor_build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_mrw_scratch/$sys_type*_hb.mrw.xml $PROJECT_ROOT/src/usr/targeting/common/xmltohb/
-        if [ $? -ne 0 ]; then
-            return $?
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
+            return ${rc}
         fi
         echo ""
         echo "Replacing $PROJECT_ROOT/src/usr/targeting/common/xmltohb/simics_P10.system.xml with $sys_type"
         cp -v $PROJECT_ROOT/src/usr/targeting/common/xmltohb/$sys_type*_hb.mrw.xml $PROJECT_ROOT/src/usr/targeting/common/xmltohb/simics_P10.system.xml
-        if [ $? -ne 0 ]; then
-            return $?
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
+            return ${rc}
         fi
     fi
 }
@@ -88,24 +94,27 @@ function checkout_hostboot_level ()
     echo ""
     echo "Checking out a new branch for $HOSTBOOT_COMMIT_HASH as $branch_name ..."
     git fetch gerrit && git checkout -b $branch_name $HOSTBOOT_COMMIT_HASH
-    if [ $? -ne 0 ]; then
-        return $?
+    rc=$?
+    if [ ${rc} -ne 0 ]; then
+        return ${rc};
     fi
 }
 
 function get_standalone_changes ()
 {
-    ssh -p 29418 hostboot.gerrit gerrit query "(intopic:bmc_standalone_patching) project:hostboot" --current-patch-set | grep -E 'change I|subject:'
-    if [ $? -ne 0 ]; then
-        return $?
+    ssh -p 29418 hostboot.gerrit gerrit query "(intopic:bmc_standalone_patching_release-${build_release}) project:hostboot" --current-patch-set | grep -E 'change I|subject:'
+    rc=$?
+    if [ ${rc} -ne 0 ]; then
+        return ${rc}
     fi
 }
 
 function gerrit_refs ()
 {
     ssh -p 29418 hostboot.gerrit gerrit query --current-patch-set "project:hostboot $1" | grep ref: | awk '{print $2}'
-    if [ $? -ne 0 ]; then
-        return $?
+    rc=$?
+    if [ ${rc} -ne 0 ]; then
+        return ${rc}
     fi
 }
 
@@ -113,8 +122,9 @@ function gerrit_pick ()
 {
     # $1 input is a commit or search string
     git fetch gerrit $(gerrit_refs $1) && git cherry-pick --strategy=recursive -X theirs FETCH_HEAD
-    if [ $? -ne 0 ]; then
-        return $?
+    rc=$?
+    if [ ${rc} -ne 0 ]; then
+        return ${rc}
     fi
 }
 
@@ -155,9 +165,10 @@ function cherrypick_standalone_patch ()
             echo "PICK $CHANGEID ${subjects[$i]}"
 
             gerrit_pick $CHANGEID
-            if [ $? -ne 0 ]; then
+            rc=$?
+            if [ ${rc} -ne 0 ]; then
                 \rm .gitlog
-                return $?
+                return ${rc}
             fi
         else
             echo "HAVE $CHANGEID ${subjects[$i]}"
@@ -167,6 +178,16 @@ function cherrypick_standalone_patch ()
 
     \rm .gitlog
 
+}
+
+function pull_pnor_xml ()
+{
+    echo "Getting the OP-BUILD PNOR defaultPnorLayout_64.xml to replace the STANDALONE pnorLayoutP10.xml to properly build patches for BMC"
+    cp -v /afs/rchland/projects/esw/$pnor_release/Builds/$pnor_build/op-build/output/build/openpower-pnor-p10*/p10Layouts/defaultPnorLayout_64.xml $PROJECT_ROOT/src/build/buildpnor/pnorLayoutP10.xml
+    rc=$?
+    if [ ${rc} -ne 0 ]; then
+        return ${rc}
+    fi
 }
 
 function verify_config_file ()
@@ -356,27 +377,45 @@ function main ()
     ################################################
     if [ "$xml_only" == false ]; then
         checkout_hostboot_level
-        if [ $? -ne 0 ]; then
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
             echo "ERROR: Couldn't checkout the hostboot level. See above messages for more info."
-            return $?
+            return ${rc};
         fi
+        # Attempt to cherry pick the needed changes onto the new release level. In some releases the commit
+        # will be missing and picked over. In recent builds it will present already and this function will be
+        # a no-op.
         cherrypick_standalone_patch
-        if [ $? -ne 0 ]; then
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
             echo "ERROR: Couldn't cherry pick the required patch. See above messages for more info."
-            return $?
+            return ${rc}
         fi
     fi
 
     if [ "$no_xml" == false ]; then
         copy_targeting_xml
-        if [ $? -ne 0 ]; then
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
             echo "ERROR: Couldn't copy over targeting xml files. See above messages for more info."
-            return $?
+            return ${rc}
         fi
     fi
 
     if [ "$xml_only" == false ]; then
         verify_config_file
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
+            echo "ERROR: Couldn't verify config file. See above messages for more info."
+            return ${rc}
+        fi
+        # Replace the existing PNOR layout (made for standalone) with the one from the release (made for hardware).
+        pull_pnor_xml
+        rc=$?
+        if [ ${rc} -ne 0 ]; then
+            echo "ERROR: Couldn't copy PNOR layout from release level. See above messages for more info."
+            return ${rc}
+        fi
 
         while true; do
             read -p " To finish setup, this script must 'make clobber' and perform 'hb simsetup' in this repo. Do that now [Y/N]? " yn
@@ -384,6 +423,7 @@ function main ()
                 [Yy] ) cleanup_repo
                        echo "Hostboot repo has been clobbered and a new sandbox for this driver has been created. You may now apply your changes, compile, prime, and patch the system."
                        echo "IMPORTANT: If you exit this shell you MUST export the correct CONFIG_FILE in the new shell to build patches again on this branch. The file is located in your project root."
+                       echo "IMPORTANT: REQUIRED to export BMC_STANDALONE_PATCHING=1 in your CUSTOMRC or in your new shell to build patches again on this branch. The file is located in your project root."
                        break ;;
                 [Nn] )
                     # Remind the user of their responsibilities. Put this notice here so it's not seen when doing copy-only actions.
@@ -402,6 +442,8 @@ function main ()
 # The user must source this script
 # otherwise it can't update the environment variable for the CONFIG_FILE
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    # export to indicate for assemble.standalone.mk which PNOR layout to model
+    export BMC_STANDALONE_PATCHING=1
     main $@
 else
     echo "ERROR: This script must be sourced in order to setup the repo properly"
