Improve setup-standalone-repo in finding the PNOR layout file
This commit updates setup-standalone-repo to check for a second
possible location for the PNOR Layout file if it is not found
in the primary location.

Change-Id: Ife85fe96d4125b00e57f3a5000153167fde87663
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/c/hostboot/+/194582
Reviewed-by: Matt Strom <matt.strom@ibm.com>
Reviewed-by: Daniel Crowell <dcrowell@us.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>

diff --git a/src/build/tools/ebmc/setup-standalone-repo b/src/build/tools/ebmc/setup-standalone-repo
--- a/src/build/tools/ebmc/setup-standalone-repo
+++ b/src/build/tools/ebmc/setup-standalone-repo
@@ -108,6 +108,12 @@ function pull_pnor_xml ()
     echo "Getting the OP-BUILD PNOR defaultPnorLayout_64.xml to replace the STANDALONE $file to properly build patches for BMC"
     cp -v /afs/rchland/projects/esw/$pnor_release/Builds/$pnor_build/op-build/output/build/openpower-pnor-${generation}*/${generation}Layouts/defaultPnorLayout_64.xml $PROJECT_ROOT/src/build/buildpnor/$file
     rc=$?
+    # If it fails, try a possible second location
+    if [ ${rc} -ne 0 ]; then
+        echo "Trying a second location for the OP-BUILD PNOR defaultPnorLayout_64.xml to replace the STANDALONE $file to properly build patches for BMC"
+        cp -v /afs/rchland/projects/esw/$pnor_release/Builds/$pnor_build/op-build_savedOutput/p11ebmc/ship/openpower-pnor-${generation}*/${generation}Layouts/defaultPnorLayout_64.xml $PROJECT_ROOT/src/build/buildpnor/$file
+        rc=$?
+    fi
     if [ ${rc} -ne 0 ]; then
         return ${rc}
     fi
