Update execute_in_sandbox to exit when sb command hits error
Change-Id: Ideb1cefc6f2f2134db11da36a00692ab198f59d5
RTC:69928
Reviewed-on: http://gfw160.austin.ibm.com:8080/gerrit/4131
Tested-by: Jenkins Server
Reviewed-by: Brian H. Horton <brianh@linux.ibm.com>
Reviewed-by: MIKE J. JONES <mjjones@us.ibm.com>
Reviewed-by: A. Patrick Williams III <iawillia@us.ibm.com>

diff --git a/src/build/tools/hb b/src/build/tools/hb
--- a/src/build/tools/hb
+++ b/src/build/tools/hb
@@ -40,6 +40,12 @@ execute_in_sandbox()
 
     ${WORKON_CMD} -c ./sandbox_execute_cmd
 
+    if [ $? -ne 0 ]; then
+        echo "Sandbox cmd failed"
+        rm ${SANDBOXBASE}/src/sandbox_execute_cmd
+        exit -1
+    fi
+
     rm ${SANDBOXBASE}/src/sandbox_execute_cmd
 }
 
