Add option to run RcdlSniffer2Perl tool during prime
This commit adds the '--src-check' option to ./hb prime. This will run
RcdlSniffer2Perl against all obj/genfiles/HB_BCxxRcdl_* files. By
default, the prime will continue even if RcdlSniffer2Perl encounters
an issue with SRCs. To halt the prime on a sniffer error, export the
environment variable PARSE_RCDL_STRICT. If PARSE_RCDL_STRICT is set to
anything other than the empty string, then the prime will run
RcdlSniffer2Perl even if --src-check is not passed in.

examples:
`./hb prime`
  - RcdlSniffer2Perl is not run. prime executes as normal

`./hb prime --src-check`
  - runs RcdlSniffer2Perl against all obj/genfiles/HB_BCxxRcdl_* files
  - sniffer fail/error will NOT fail the prime

`export PARSE_RCDL_STRICT='' ; ./hb prime`
  - RcdlSniffer2Perl is not run. prime executes as normal

`export PARSE_RCDL_STRICT=1 ; ./hb prime`
  - runs RcdlSniffer2Perl against all obj/genfiles/HB_BCxxRcdl_* files
  - sniffer fail/error will fail the prime

`export PARSE_RCDL_STRICT=1 ; ./hb prime --src-check`
  - runs RcdlSniffer2Perl against all obj/genfiles/HB_BCxxRcdl_* files
  - sniffer fail/error will fail the prime

Change-Id: I7cb1046a97fba0e723546be4a4807b5c4bfb1e09
RTC: 257736
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/115820
Reviewed-by: Michael Baiocchi <mbaiocch@us.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins OP Build CI <op-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins Combined Simics CI <combined-simics-ci+hostboot@us.ibm.com>
Tested-by: Jenkins OP HW <op-hw-jenkins+hostboot@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Tested-by: Hostboot CI <hostboot-ci+hostboot@us.ibm.com>
Reviewed-by: Christian R Geddes <crgeddes@us.ibm.com>
Reviewed-by: Daniel M Crowell <dcrowell@us.ibm.com>

diff --git a/src/build/tools/hbDistribute b/src/build/tools/hbDistribute
--- a/src/build/tools/hbDistribute
+++ b/src/build/tools/hbDistribute
@@ -129,6 +129,11 @@ do
             shift
         ;;
 
+        "--src-check")
+            SNIFFER_CHECK=1
+            shift
+        ;;
+
         "--corrupt")
             # Format is "--corrupt <partition[=pro|unpro]>"
             CORRUPT_PARAMS="$CORRUPT_PARAMS $1"
@@ -212,6 +217,47 @@ else
         echo "ERROR: Not in a git repo."
         exit
     fi
+fi
+
+# if requested, pull in RcdlSniffer2Perl and run against all HB_BCxxRcdl files
+if [[ $SNIFFER_CHECK -eq 1 || -n ${PARSE_RCDL_STRICT} ]]; then
+
+    if [[ ! -d "${PROJECT_ROOT}/standalone/pubs-tools" ]];then
+        mkdir -p ${PROJECT_ROOT}/standalone/pubs-tools
+        git clone git@github.ibm.com:open-power/pubs-tools.git ${PROJECT_ROOT}/standalone/pubs-tools
+    fi
+
+    set +e
+
+    # if genfiles dir does not exist and strict parsing is on, fail the prime
+    if [[ ! -d "${PROJECT_ROOT}/obj/genfiles" && -n ${PARSE_RCDL_STRICT} ]]; then
+        echo "PARSE_RCDL_STRICT is set but ${PROJECT_ROOT}/obj/genfiles does not exist"
+        exit -1
+    else
+        echo "Running RcdlSniffer2Perl against all HB_BCxxRcdl_ files"
+        for fname in $(ls ${PROJECT_ROOT}/obj/genfiles/HB_BCxxRcdl_*); do
+
+             ${PROJECT_ROOT}/standalone/pubs-tools/RcdlSniffer2Perl PROFILE=${PROJECT_ROOT}/standalone/pubs-tools/snifferStandardProfile.h $fname 2> ${PROJECT_ROOT}/standalone/pubs-tools/sniffer.log > /dev/null
+             rc=$?
+             # if RcdlSniffer2Perl encounters an error
+             if [[ "$rc" -ne 0 ]]; then
+                 echo "RcdlSniffer2Perl failed with $rc on $fname error msg saved in ${PROJECT_ROOT}/standalone/pubs-tools/sniffer.log"
+                 cat ${PROJECT_ROOT}/standalone/pubs-tools/sniffer.log
+                 # and if PARSE_RCDL_STRICT is set to something other than the empty string
+                 if [[ -n ${PARSE_RCDL_STRICT} ]]; then
+                     # stop the prime
+                     exit -1
+                 else
+                     # otherwise break the loop so duplicate errors from
+                     # different RCDL files aren't displayed to the screen
+                     # and continue prime
+                     break
+                 fi
+             fi
+
+        done
+    fi
+    set -e
 fi
 
 # Point to various signing related path components
