Temporary fix to handle autosim hangs on real code errors
Change-Id: I6c67b42ee967905b7ae63408c6168db36b078b04
Reviewed-on: http://ralgit01.raleigh.ibm.com/gerrit1/21773
Tested-by: Jenkins Server
Reviewed-by: Martin Gloff <mgloff@us.ibm.com>
Reviewed-by: Christian R. Geddes <crgeddes@us.ibm.com>
Reviewed-by: Daniel M. Crowell <dcrowell@us.ibm.com>

diff --git a/src/build/citest/autocitest b/src/build/citest/autocitest
--- a/src/build/citest/autocitest
+++ b/src/build/citest/autocitest
@@ -299,6 +299,15 @@ while [ $(($modsstarted)) -lt 1 -o $(($modsstarted)) -ne $(($modscompleted)) ]; 
 
     echo "ModulesStarted:ModulesCompleted  => $modsstarted:$modscompleted"
 
+    # @TODO RTC:149210 temporary fix for autosim hangs on real code errors. For some reason
+    # when we hit an actual bug and simics halts, the autosim commands hang
+    # causing this loop to take >8 hours.
+    if [ -z $modsstarted ] && [ -z $modscompleted ]; then
+        echo "ERROR: autosim hanging on real code errors, temporarily catching early"
+        echo "See archived hbTracMerg for more info"
+        exit 1
+    fi
+
     if [ "$loopcount" -gt 90 ];   then
         echo    "ERROR: timed out after 15 minutes"
         autosim $NOWIN --simcmd   "hb-Ps"
