Finishing up PNOR RP code (RTC Task 3440) -Add calls to mm_alloc_block -Fix error responses to message -Cleanup some error handling -Code review updates
Final piece of the PNOR puzzle - Task 3389
-Also added a check to autocitest that will catch initialization fails.
-Added some error printks to message interface
-Disabled test_messageReadWrite testcase

Change-Id: I4f1207138a6cf4f86cf2b6f3f81fc5885b02699d
Reviewed-on: http://gfw160.austin.ibm.com:8080/gerrit/252
Tested-by: Jenkins Server
Reviewed-by: Daniel M. Crowell <dcrowell@us.ibm.com>

diff --git a/src/build/citest/autocitest b/src/build/citest/autocitest
--- a/src/build/citest/autocitest
+++ b/src/build/citest/autocitest
@@ -445,17 +445,25 @@ timestamp=`date +'%H:%M:%S'`
 
 echo    "----------------- Printk Buffer -------------------"
 cat $SBXHOME/testprintk.log
+shutdown_code="$(grep --text 'Shutdown Requested' $SBXHOME/testprintk.log | awk -F '= 0x' '{ print $2 }')"
+
 
 echo    "----------------- traceHB Buffer -------------------"
 cat $SBXHOME/traceHB.log
 
 
-
+initfail=0
+echo "Shutdown Code = $shutdown_code"
+if [ "${shutdown_code}" != "0000000001230000" ]
+then
+ echo "**ERROR : System did not initialize and/or shutdown properly**"
+ initfail=1
+fi
 
 echo
 echo    "==================================================="
 if [ $timeout = 0 ] ; then
-    echo    "$timestamp Finished autocitest with no errors."
+    echo    "$timestamp Finished autocitest with no Cxx errors."
 else
     echo    "$timestamp Failed autocitest, modules timed out."
     echo    "    failed modules:  $timeout"
@@ -478,6 +486,10 @@ if [ 0 !=  $(($failedtests)) ] ; then
 fi
 if [ 0 != $(($warnings)) ] ; then
     echo "$warnings testcase warnings found."
+    exit 1
+fi
+if [ 0 != $(($initfail)) ] ; then
+    echo "Initialization Failure"
     exit 1
 fi
 
