TS_TRACE now dumps to trace buffer instead of printk
-Minor change to cxxtestgen.pl script to bump the suite name and add whitespace
- resolve conflicts in makefile and cxxtestgen.pl
- fix TS_TRACE
- add fixes from code review
- add debug messages to trace modules not finishing problem
- line over 80 chars, remove 10 sec delay
- add 5 min timeout to autocitest
- change check interval to 5 seconds instead of 30 seconds

Change-Id: I11f18fbeed007590a4ca70c45d109071474a9864
Reviewed-on: http://gfw160.austin.ibm.com:8080/gerrit/154
Tested-by: Jenkins Server
Reviewed-by: A. Patrick Williams III <iawillia@us.ibm.com>

diff --git a/src/build/citest/autocitest b/src/build/citest/autocitest
--- a/src/build/citest/autocitest
+++ b/src/build/citest/autocitest
@@ -268,14 +268,23 @@ mods_completed_addr=`grep "CxxTest::g_ModulesCompleted" \
 echo "Wait for unit test completion."
 modsstarted=0
 modscompleted=0
+loopcount=0
 while [ $modsstarted -lt 1 -o $modsstarted -ne $modscompleted ]; do
-    sleep 1
+    sleep 5
+    ((loopcount++))     # increment loopcount
     autosim $NOWIN --simcmd   "phys_mem.read 0x$mods_started_addr 0x08"     1> $SBXHOME/modsstarted.log  2> /dev/null
     modsstarted=`cat $SBXHOME/modsstarted.log | xargs echo -n`
     autosim $NOWIN --simcmd   "phys_mem.read 0x$mods_completed_addr 0x08"     1> $SBXHOME/modscompleted.log  2> /dev/null
     modscompleted=`cat $SBXHOME/modscompleted.log | xargs echo -n`
 
-    echo "$modsstarted:$modscompleted"
+    echo "ModulesStarted:ModulesCompleted  => $modsstarted:$modscompleted"
+    
+    if [ "$loopcount" -gt 60 ];   then
+        echo    "ERROR: timed out after 5 minutes"
+        stopsim
+        stopserver
+        exit 1
+    fi
 done
 
 
