Build error log parsers during Jenkins build.
Change-Id: Ia404970a84897d1a89e1f86a18220fc0199e4df1
RTC: 66441
Reviewed-on: http://gfw160.aus.stglabs.ibm.com:8080/gerrit/10674
Tested-by: Jenkins Server
Reviewed-by: Daniel M. Crowell <dcrowell@us.ibm.com>
Reviewed-by: STEPHEN M. CPREK <smcprek@us.ibm.com>
Reviewed-by: A. Patrick Williams III <iawillia@us.ibm.com>

diff --git a/src/build/citest/build-script b/src/build/citest/build-script
--- a/src/build/citest/build-script
+++ b/src/build/citest/build-script
@@ -54,6 +54,10 @@ fi
 # Add Hostboot files to simics sandbox.
 populate-sandbox || exit -1
 
+# Start errl parser building.
+build-errl-parsers > errl-parsers.log 2>&1 &
+ERRLPARSERS_PID=$!
+
 # Start CxxTest Simics execution.
 cxxtest-start.sh || exit -1
 
@@ -64,6 +68,14 @@ if [ $? -eq 0 ]; then
 else
     echo "----Copyright check failed."
     cat copyright.log
+    exit -1
+fi
+
+# Check errl parser completion.
+wait $ERRLPARSERS_PID
+if [ $? -ne 0 ]; then
+    echo "----Error parsers failed."
+    cat errl-parsers.log
     exit -1
 fi
 
