Change CONFIG_SECUREBOOT default to n
Modify build pnor process to drive logic off of CONFIG_SECUREBOOT
Support multi config job for secure and unsecure hostboot CI

RTC:157288
Change-Id: Ia3028e22215d7008cf09bde4b071700a43302ca7
Reviewed-on: http://ralgit01.raleigh.ibm.com/gerrit1/26902
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Reviewed-by: Nicholas E. Bofferding <bofferdn@us.ibm.com>
Tested-by: Jenkins OP Build CI <op-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins OP HW <op-hw-jenkins+hostboot@us.ibm.com>
Reviewed-by: Michael Baiocchi <mbaiocch@us.ibm.com>
Reviewed-by: Daniel M. Crowell <dcrowell@us.ibm.com>

diff --git a/src/build/citest/build-script b/src/build/citest/build-script
--- a/src/build/citest/build-script
+++ b/src/build/citest/build-script
@@ -6,7 +6,7 @@
 #
 # OpenPOWER HostBoot Project
 #
-# Contributors Listed Below - COPYRIGHT 2014,2015
+# Contributors Listed Below - COPYRIGHT 2014,2016
 # [+] International Business Machines Corp.
 #
 #
@@ -24,6 +24,15 @@
 #
 # IBM_PROLOG_END_TAG
 
+# Handle Multi-Config options
+CONFIG_FILE=""
+COMPILE_ONLY=0
+if [ "$CONFIG" == "SECUREBOOT" ]; then
+    CONFIG_FILE="secureboot.config"
+    export SECURITY_HW_POLICY="1"
+    export SECURITY_SW_POLICY="1"
+fi
+
 if [ -z $PROJECT_ROOT ]; then
     source "$WORKSPACE/env.bash"
 fi
@@ -32,52 +41,75 @@ source "$PROJECT_ROOT/src/build/citest/setup-env"
 
 #export HOSTBOOT_DEBUG=1    #-- Ensure printkd / tracd is compiled in.
 
-# Check copyright.
-check-copyright > copyright.log 2>&1 &
-COPYRIGHT_PID=$!
+# Only run copyright check in default mode
+if [ "${CONFIG_FILE}" == "" ]; then
+    # Check copyright.
+    check-copyright > copyright.log 2>&1 &
+    COPYRIGHT_PID=$!
+fi
 
-# Create simics sandbox.
-create-sandbox > create-sandbox.log 2>&1 &
-CREATESANDBOX_PID=$!
+# Only create sandbox if not running in COMPILE_ONLY mode
+if [ ${COMPILE_ONLY} -eq 0 ]; then
+    # Create simics sandbox.
+    create-sandbox > create-sandbox.log 2>&1 &
+    CREATESANDBOX_PID=$!
+fi
 
 # Build Hostboot.
-make -j32 || exit -1
-
-# Check copyright completion.
-wait $COPYRIGHT_PID
-if [ $? -eq 0 ]; then
-    cat copyright.log
+if [ "${CONFIG_FILE}" != "" ]; then
+    CONFIG_FILE_PATH="src/build/configs/${CONFIG_FILE}"
+    if [ -f $CONFIG_FILE_PATH ]; then
+        echo "Building using config = $CONFIG_FILE_PATH"
+        CONFIG_FILE=$CONFIG_FILE_PATH make -j32 || exit -1
+    else
+        echo "Config file not found: $CONFIG_FILE_PATH"
+        exit -1;
+    fi
 else
-    echo "----Copyright check failed."
-    cat copyright.log
-    exit -1
+    echo "Building using default config"
+    make -j32 || exit -1
 fi
 
-# Check sandbox create completion.
-wait $CREATESANDBOX_PID
-if [ $? -eq 0 ]; then
-    cat create-sandbox.log
-else
-    echo "----Sandbox creation failed."
-    cat create-sandbox.log
-    exit -1
+# Only check copyright check in default mode
+if [ "${CONFIG_FILE}" == "" ]; then
+    # Check copyright completion.
+    wait $COPYRIGHT_PID
+    if [ $? -eq 0 ]; then
+        cat copyright.log
+    else
+        echo "----Copyright check failed."
+        cat copyright.log
+        exit -1
+    fi
 fi
 
-# Add Hostboot files to simics sandbox.
-populate-sandbox || exit -1
+# Only check sandbox creationg and run simics if not running in COMPILE_ONLY mode
+if [ ${COMPILE_ONLY} -eq 0 ]; then
+    # Check sandbox create completion.
+    wait $CREATESANDBOX_PID
+    if [ $? -eq 0 ]; then
+        cat create-sandbox.log
+    else
+        echo "----Sandbox creation failed."
+        cat create-sandbox.log
+        exit -1
+    fi
 
-# Start errl parser building.
-build-errl-parsers > errl-parsers.log 2>&1 &
-ERRLPARSERS_PID=$!
+    # Add Hostboot files to simics sandbox.
+    populate-sandbox || exit -1
 
-# Start CxxTest Simics execution.
-cxxtest-start.sh || exit -1
+    # Start errl parser building.
+    build-errl-parsers > errl-parsers.log 2>&1 &
+    ERRLPARSERS_PID=$!
 
-# Check errl parser completion.
-wait $ERRLPARSERS_PID
-if [ $? -ne 0 ]; then
-    echo "----Error parsers failed."
-    cat errl-parsers.log
-    exit -1
+    # Start CxxTest Simics execution.
+    cxxtest-start.sh || exit -1
+
+    # Check errl parser completion.
+    wait $ERRLPARSERS_PID
+    if [ $? -ne 0 ]; then
+        echo "----Error parsers failed."
+        cat errl-parsers.log
+        exit -1
+    fi
 fi
-
