Short circuit Jenkins job if there are commit verification errors
Change-Id: I2bff607b8a76229d41bf538fd3a24f594bdf21fd
Reviewed-on: http://gfw160.aus.stglabs.ibm.com:8080/gerrit/20978
Tested-by: Jenkins Server
Tested-by: Jenkins OP Build CI
Tested-by: FSP CI Jenkins
Tested-by: Jenkins OP HW
Reviewed-by: PRACHI GUPTA <pragupta@us.ibm.com>
Reviewed-by: Elizabeth Liner <eliner@us.ibm.com>
Reviewed-by: A. Patrick Williams III <iawillia@us.ibm.com>

diff --git a/src/build/citest/build-script b/src/build/citest/build-script
--- a/src/build/citest/build-script
+++ b/src/build/citest/build-script
@@ -43,6 +43,16 @@ CREATESANDBOX_PID=$!
 # Build Hostboot.
 make -j32 || exit -1
 
+# Check copyright completion.
+wait $COPYRIGHT_PID
+if [ $? -eq 0 ]; then
+    cat copyright.log
+else
+    echo "----Copyright check failed."
+    cat copyright.log
+    exit -1
+fi
+
 # Check sandbox create completion.
 wait $CREATESANDBOX_PID
 if [ $? -eq 0 ]; then
@@ -62,16 +72,6 @@ ERRLPARSERS_PID=$!
 
 # Start CxxTest Simics execution.
 cxxtest-start.sh || exit -1
-
-# Check copyright completion.
-wait $COPYRIGHT_PID
-if [ $? -eq 0 ]; then
-    cat copyright.log
-else
-    echo "----Copyright check failed."
-    cat copyright.log
-    exit -1
-fi
 
 # Check errl parser completion.
 wait $ERRLPARSERS_PID
